#!/usr/bin/lua

local util = require 'gluon.util'
local uci = require('luci.model.uci').cursor()

-- fix up duplicate mac addresses (for meshing)
uci:set('network', 'wan', 'macaddr', util.generate_mac(3))
uci:set('network', 'mesh_lan', 'macaddr', util.generate_mac(6))
uci:save('network')
